<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>__AUTOCNC_BOT_ROOT_NAMESPACE__.Tests</RootNamespace>
    <AssemblyName>__AUTOCNC_BOT_ROOT_NAMESPACE__.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\__AUTOCNC_BOT_IDENTIFIER__.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoCnC.Sdk" Version="$(AutoCnCVersion)" ExcludeAssets="runtime" />
    <PackageReference Include="AutoCnC.Core" Version="$(AutoCnCVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" PrivateAssets="all" />
    <PackageReference Include="NUnit" Version="4.2.2" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
