<#
.SYNOPSIS
    Writes the duel lab's measured matchups into the Reference bot as a C# table.

.DESCRIPTION
    Reads matchups.json from scripts/duel-lab-report.ps1 and writes
    bots/Reference/Logic/MatchupTable.cs: the equal-cost margins, blind and with vision, as
    integers from -100 to +100. The bot needs no file access and no engine types to use it.
    Regenerate after a lab run whenever the engine or the rules change.

.PARAMETER MatchupsPath
    matchups.json from a duel lab run.

.PARAMETER OutputPath
    The C# file to write.
#>
[CmdletBinding()]
param(
    [string]$MatchupsPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'tools\DuelLab\results\matchups.json'),
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'bots\Reference\Logic\MatchupTable.cs')
)

$ErrorActionPreference = 'Stop'
$data = Get-Content -LiteralPath $MatchupsPath -Raw | ConvertFrom-Json
$units = @($data.units)

function Row($table, [string]$unit) {
    $cells = foreach ($o in $units) {
        if ($o -eq $unit) { '0' } else {
            $m = $table.$unit.$o
            if ($null -eq $m) { '0' } else { [string][int][math]::Round([double]$m * 100) }
        }
    }
    "`t`t`t{ " + ($cells -join ', ') + ' },'
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('#region Copyright & License Information')
$lines.Add('/*')
$lines.Add(' * Copyright (c) The AutoC&C Developers and Contributors')
$lines.Add(' * This file is part of AutoC&C, which is free software. It is made')
$lines.Add(' * available to you under the terms of the GNU General Public License')
$lines.Add(' * as published by the Free Software Foundation, either version 3 of')
$lines.Add(' * the License, or (at your option) any later version. For more')
$lines.Add(' * information, see LICENSE.')
$lines.Add(' */')
$lines.Add('#endregion')
$lines.Add('')
$lines.Add('// <auto-generated>')
$lines.Add('//   Written by scripts/export-bot-matchups.ps1 from the duel lab (tools/DuelLab). Do not edit')
$lines.Add('//   by hand: rerun ./scripts/duel-lab.ps1 and then that script.')
$lines.Add("//   Seeds: $(@($data.seeds) -join ', ')")
$lines.Add('// </auto-generated>')
$lines.Add('')
$lines.Add('using System;')
$lines.Add('using System.Collections.Generic;')
$lines.Add('')
$lines.Add('namespace AutoCnC.Reference.Logic')
$lines.Add('{')
$lines.Add('	/// <summary>')
$lines.Add('	/// How every combat unit fares against every other one, measured by the engine rather than')
$lines.Add('	/// inferred from the rules. See docs/unit-matchups.md for the readable version.')
$lines.Add('	/// </summary>')
$lines.Add('	/// <remarks>')
$lines.Add('	/// A margin is the share of the opponent''s value destroyed minus the share of your own,')
$lines.Add('	/// from 3,600 credits a side meeting on open ground, times 100: +100 is a clean sweep,')
$lines.Add('	/// -100 is being swept. "Spotted" is the same fight with both sides seeing the whole lane,')
$lines.Add('	/// which is what long-range units are worth when something spots for them. Static rules')
$lines.Add('	/// knowledge, the same a player reads from the encyclopedia, so using it is fair play.')
$lines.Add('	/// </remarks>')
$lines.Add('	public static class MatchupTable')
$lines.Add('	{')
$lines.Add('		public static IReadOnlyList<string> Units { get; } =')
$lines.Add('		[')
$lines.Add("			" + (($units | ForEach-Object { '"' + $_ + '"' }) -join ', '))
$lines.Add('		];')
$lines.Add('')
$lines.Add('		static readonly sbyte[,] Blind =')
$lines.Add('		{')
foreach ($u in $units) { $lines.Add((Row $data.cost $u)) }
$lines.Add('		};')
$lines.Add('')
$lines.Add('		static readonly sbyte[,] Spotted =')
$lines.Add('		{')
foreach ($u in $units) { $lines.Add((Row $data.costSpotted $u)) }
$lines.Add('		};')
$lines.Add('')
$lines.Add('		static readonly Dictionary<string, int> Index = BuildIndex();')
$lines.Add('')
$lines.Add('		static Dictionary<string, int> BuildIndex()')
$lines.Add('		{')
$lines.Add('			var index = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);')
$lines.Add('			for (var i = 0; i < Units.Count; i++)')
$lines.Add('				index[Units[i]] = i;')
$lines.Add('			return index;')
$lines.Add('		}')
$lines.Add('')
$lines.Add('		/// <summary>Whether the lab measured this actor type.</summary>')
$lines.Add('		public static bool Knows(string actorType) =>')
$lines.Add('			!string.IsNullOrEmpty(actorType) && Index.ContainsKey(actorType);')
$lines.Add('')
$lines.Add('		/// <summary>')
$lines.Add('		/// How well <paramref name="unit"/> does against <paramref name="opponent"/> at equal cost,')
$lines.Add('		/// -100 to +100, or 0 when either was not measured.')
$lines.Add('		/// </summary>')
$lines.Add('		public static int Margin(string unit, string opponent, bool spotted = false)')
$lines.Add('		{')
$lines.Add('			if (unit == null || opponent == null')
$lines.Add('				|| !Index.TryGetValue(unit, out var row) || !Index.TryGetValue(opponent, out var column))')
$lines.Add('				return 0;')
$lines.Add('')
$lines.Add('			return spotted ? Spotted[row, column] : Blind[row, column];')
$lines.Add('		}')
$lines.Add('	}')
$lines.Add('}')

$lines | Set-Content -LiteralPath $OutputPath -Encoding utf8
Write-Host "==> $OutputPath ($($units.Count) units)" -ForegroundColor Cyan
