#region Copyright & License Information
/*
 * Copyright (c) The AutoC&C Developers and Contributors
 * This file is part of AutoC&C, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see LICENSE.
 */
#endregion

// <auto-generated>
//   Written by scripts/export-bot-matchups.ps1 from the duel lab (tools/DuelLab). Do not edit
//   by hand: rerun ./scripts/duel-lab.ps1 and then that script.
//   Seeds: 1, 2, 3
// </auto-generated>

using System;
using System.Collections.Generic;

namespace AutoCnC.Reference.Logic
{
	/// <summary>
	/// How every combat unit fares against every other one, measured by the engine rather than
	/// inferred from the rules. See docs/unit-matchups.md for the readable version.
	/// </summary>
	/// <remarks>
	/// A margin is the share of the opponent's value destroyed minus the share of your own,
	/// from 3,600 credits a side meeting on open ground, times 100: +100 is a clean sweep,
	/// -100 is being swept. "Spotted" is the same fight with both sides seeing the whole lane,
	/// which is what long-range units are worth when something spots for them. Static rules
	/// knowledge, the same a player reads from the encyclopedia, so using it is fair play.
	/// </remarks>
	public static class MatchupTable
	{
		public static IReadOnlyList<string> Units { get; } =
		[
			"e1", "e2", "e3", "e4", "e5", "rmbo", "jeep", "apc", "mtnk", "htnk", "msam", "bggy", "bike", "ltnk", "ftnk", "stnk", "arty", "mlrs", "orca", "heli"
		];

		static readonly sbyte[,] Blind =
		{
			{ 0, 24, 92, 58, 71, 86, -53, 60, 68, -53, 43, -34, 86, 77, -88, 88, -2, 64, -58, -37 },
			{ -24, 0, 86, 45, 59, 73, -19, 78, 83, 39, 15, -14, 85, 87, -42, 84, -30, 36, -88, -65 },
			{ -92, -86, 0, -90, -86, -72, -58, 75, 78, 2, -30, -62, 75, 84, -46, 69, -54, 53, 88, 57 },
			{ -58, -45, 90, 0, 51, 61, 4, 46, 54, -66, 62, 13, 83, 60, -90, 90, 18, 46, -45, -74 },
			{ -71, -59, 86, -51, 0, 47, -45, 84, 89, 61, 58, -35, 85, 92, -42, 83, -45, 28, -44, -87 },
			{ -86, -73, 72, -61, -47, 0, -100, -100, -99, -98, -99, -100, -97, -100, -99, -81, -66, -67, -100, -100 },
			{ 53, 19, 58, -4, 45, 100, 0, -81, -87, -92, -7, -24, 51, -84, -93, 53, 23, 91, -100, -100 },
			{ -60, -78, -75, -46, -84, 100, 81, 0, -83, -90, 35, 78, 32, -76, -57, 49, 35, 97, 83, 88 },
			{ -68, -83, -78, -54, -89, 99, 87, 83, 0, -57, 52, 83, 46, 43, 50, 48, 53, 99, -100, -62 },
			{ 53, -39, -2, 66, -61, 98, 92, 90, 57, 0, 53, 90, 64, 62, 73, 58, 54, 99, 78, 88 },
			{ -43, -15, 30, -62, -58, 99, 7, -35, -52, -53, 0, 4, 43, -38, -35, 33, -19, 67, -100, -100 },
			{ 34, 14, 62, -13, 35, 100, 24, -78, -83, -90, -4, 0, 55, -84, -90, 60, -20, 91, -95, -98 },
			{ -86, -85, -75, -83, -85, 97, -51, -32, -46, -64, -43, -55, 0, -28, -47, 2, -43, 86, 56, 62 },
			{ -77, -87, -84, -60, -92, 100, 84, 76, -43, -62, 38, 84, 28, 0, 28, 40, 43, 98, -94, -75 },
			{ 88, 42, 46, 90, 42, 99, 93, 57, -50, -73, 35, 90, 47, -28, 0, 39, 27, 94, -100, -94 },
			{ -88, -84, -69, -90, -83, 81, -53, -49, -48, -58, -33, -60, -2, -40, -39, 0, -61, 92, 62, 55 },
			{ 2, 30, 54, -18, 45, 66, -23, -35, -53, -54, 19, 20, 43, -43, -27, 61, 0, 58, -100, -100 },
			{ -64, -36, -53, -46, -28, 67, -91, -97, -99, -99, -67, -91, -86, -98, -94, -92, -58, 0, 85, 84 },
			{ 58, 88, -88, 45, 44, 100, 100, -83, 100, -78, 100, 95, -56, 94, 100, -62, 100, -85, 0, 4 },
			{ 37, 65, -57, 74, 87, 100, 100, -88, 62, -88, 100, 98, -62, 75, 94, -55, 100, -84, -4, 0 },
		};

		static readonly sbyte[,] Spotted =
		{
			{ 0, 35, 94, 61, 70, 89, -56, 60, 67, -53, 37, -36, 87, 78, -89, 88, -21, 66, -57, -51 },
			{ -35, 0, 86, 48, 58, 67, -6, 80, 84, 40, 13, -15, 88, 87, -37, 84, -26, 39, -64, -56 },
			{ -94, -86, 0, -91, -85, -66, -60, 75, 79, 5, -75, -70, 77, 84, -24, 67, -90, 64, 88, 48 },
			{ -61, -48, 91, 0, 54, 67, 8, 47, 53, -65, 57, -7, 83, 61, -92, 90, 3, 45, -30, -74 },
			{ -70, -58, 85, -54, 0, 34, -43, 84, 89, 58, 43, -30, 84, 91, -55, 84, -37, 36, -56, -93 },
			{ -89, -67, 66, -67, -34, 0, -100, -100, -99, -97, -97, -100, -96, -100, -99, -83, -72, -33, -100, -100 },
			{ 56, 6, 60, -8, 43, 100, 0, -81, -87, -92, 37, -31, 55, -84, -92, 60, 20, 92, -100, -100 },
			{ -60, -80, -75, -47, -84, 100, 81, 0, -83, -90, 33, 78, 29, -78, -58, 49, 38, 97, 83, 88 },
			{ -67, -84, -79, -53, -89, 99, 87, 83, 0, -51, 40, 83, 44, 46, 48, 53, 36, 99, -100, -54 },
			{ 53, -40, -5, 65, -58, 97, 92, 90, 51, 0, 45, 90, 65, 63, 74, 58, 45, 99, 78, 88 },
			{ -37, -13, 75, -57, -43, 97, -37, -33, -40, -45, 0, -18, 78, -48, -41, 88, 33, 86, -100, -100 },
			{ 36, 15, 70, 7, 30, 100, 31, -78, -83, -90, 18, 0, 60, -84, -92, 62, 20, 91, -100, -98 },
			{ -87, -88, -77, -83, -84, 96, -55, -29, -44, -65, -78, -60, 0, -34, -40, -6, -64, 89, 55, 61 },
			{ -78, -87, -84, -61, -91, 100, 84, 78, -46, -63, 48, 84, 34, 0, 28, 40, 31, 98, -100, -90 },
			{ 89, 37, 24, 92, 55, 99, 92, 58, -48, -74, 41, 92, 40, -28, 0, 40, 21, 96, -98, -100 },
			{ -88, -84, -67, -90, -84, 83, -60, -49, -53, -58, -88, -62, 6, -40, -40, 0, -77, 88, 65, 53 },
			{ 21, 26, 90, -3, 37, 72, -20, -38, -36, -45, -33, -20, 64, -31, -21, 77, 0, 79, -100, -100 },
			{ -66, -39, -64, -45, -36, 33, -92, -97, -99, -99, -86, -91, -89, -98, -96, -88, -79, 0, 85, 87 },
			{ 57, 64, -88, 30, 56, 100, 100, -83, 100, -78, 100, 100, -55, 100, 98, -65, 100, -85, 0, -3 },
			{ 51, 56, -48, 74, 93, 100, 100, -88, 54, -88, 100, 98, -61, 90, 100, -53, 100, -87, 3, 0 },
		};

		static readonly Dictionary<string, int> Index = BuildIndex();

		static Dictionary<string, int> BuildIndex()
		{
			var index = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
			for (var i = 0; i < Units.Count; i++)
				index[Units[i]] = i;
			return index;
		}

		/// <summary>Whether the lab measured this actor type.</summary>
		public static bool Knows(string actorType) =>
			!string.IsNullOrEmpty(actorType) && Index.ContainsKey(actorType);

		/// <summary>
		/// How well <paramref name="unit"/> does against <paramref name="opponent"/> at equal cost,
		/// -100 to +100, or 0 when either was not measured.
		/// </summary>
		public static int Margin(string unit, string opponent, bool spotted = false)
		{
			if (unit == null || opponent == null
				|| !Index.TryGetValue(unit, out var row) || !Index.TryGetValue(opponent, out var column))
				return 0;

			return spotted ? Spotted[row, column] : Blind[row, column];
		}
	}
}
